Тема: Компоненты
js-tasks-ru/vue-20241213_vladimir-garbuzzov pull request #4
Opened 2024-12-26 20:05 UTC by Vladimir2011

Решение всех задач темы "Компоненты"

2024-12-26 20:05 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-12-27 22:07 UTC, ShGKme requested changes

2024-12-27 22:07 UTC, ShGKme commented on 03-components/30-removable-emails/MarkedEmailsApp.js
> +      <EmailList :emails="markedEmails" @removeEmail="removeEmailByIndex($event)" />
`@removeEmail="removeEmailByIndex($event)"` - тоже что `@removeEmail="removeEmailByIndex"`

2024-12-27 22:07 UTC, ShGKme commented on 03-components/50-weather-components/WeatherCard.js
> +    const { alert, current, geographic_name } = props.weatherItem
Здесь при деструктуризации параметра теряется реактивность. Если в `weatherItem` придёт новый объект, или даже поменяются его свойства - в компоненте значение не обновится, так как параметры при деструктуризации получили значения, которые были при инициализации. 

Связи между реактивной переменной `props` и новыми переменными - нет. Нужно или работать напрямую с `props`, или использовать `toRef`.

https://vuejs.org/api/reactivity-utilities.html#toref

2024-12-27 22:07 UTC, ShGKme commented on 03-components/50-weather-components/WeatherApp.js
> +})
Не относится напрямую к этой задаче, но вместо модификации данных после получения лучше делать эти вычисления уже там, где эти данные используются.

В противном случае:
1. Нужно помнить про этим модификации при обновлении данных, особенно таких как `isNight`
2. Поменялся тип данных

2024-12-29 14:03 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-12-29 17:00 UTC, ShGKme requested changes

2024-12-29 17:00 UTC, ShGKme commented on 03-components/50-weather-components/WeatherCard.js
> +    const { alert, geographic_name, current } = weatherItem.value
Здесь проблема с реактивностью частично осталось.
`weatherItem` из `props` за счёт `toRef` достаётся с сохранением связи.

Но вот деструктуризация `weatherItem.value` потом снова теряет реактивность. Созданы новые переменные, у которых только начальное значение взято из параметра. Но при обновлении объекта `weatherItem` ранее созданные новые переменные `alert` и другие уже не поменяются.

Здесь тоже нужен либо `toRef`, либо `toRefs`, либо использовать без новых переменных.

2024-12-29 17:00 UTC, ShGKme commented on 03-components/50-weather-components/WeatherCard.js
> +    })
Такое изменение принимается. Но лучше разделять. Вместо вычисления целого нового объекта нового типа (с новыми полями), который будет вычисляться заново при изменении любого поля объекта, лучше сделать три вычисляемых свойства `temp`, `pressure`, `isNight`

2024-12-29 18:58 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-12-29 19:16 UTC, ShGKme approved these changes

2024-12-29 19:18 UTC, merged